Alpha version reactions
overkam/reactions pull request #2
Opened 2018-10-24 15:38 UTC by overkam

change css to js, use classes

2018-10-24 15:48 UTC, PolinaShneider requested changes

2018-10-24 15:48 UTC, PolinaShneider commented on reactions.css
> +		height: 50px;
Следи за табуляцией. У всех свойств должны быть одинаковые отступы. У тебя они сейчас скачут.

2018-10-24 15:48 UTC, PolinaShneider commented on reactions.css
> +		}
Открывающие и закрывающие скобки должны быть на одном уровне:

2018-10-24 15:48 UTC, PolinaShneider commented on reactions.html
> +    class Reactions {
JS вынести в отдельный файл и подключать к .html

2018-10-24 15:48 UTC, PolinaShneider commented on reactions.html
> +<div id=blocktext></div>
На странице не должно быть закомментированного текста. Либо раскомментировать, либо удалить.

2018-10-24 15:48 UTC, PolinaShneider commented on reactions.css
> +#blockemoji {
Лучше писать стили по `.class`, а не по `#id`

2018-10-24 16:36 UTC, overkam commented on reactions.html
> +<div id=blocktext></div>
мне он тут нужен пока, чтобы знать, как должен выглядеть результат от js, как сделаю, удалю

2018-10-25 19:21 UTC, PolinaShneider requested changes

2018-10-25 19:21 UTC, PolinaShneider commented on reactions.css
> +		width: 50px;
Отступы слишком большие. Сделай 4 пробела

2018-10-25 19:21 UTC, PolinaShneider commented on reactions.css
> +		position: static;
`position: static` — свойство по умолчанию. Вряд ли тебе его нужно вручную задавать

2018-10-25 19:21 UTC, PolinaShneider commented on reactions.css
> +		width: 60%;
Табуляция поехала

2018-10-25 19:21 UTC, PolinaShneider commented on reactions.css
> +#blockemoji {
Почему стили всё также названы по `#id`?

2018-10-25 19:21 UTC, PolinaShneider commented on reactions.html
> +<link rel="stylesheet" type="text/css" href="reactions.css">
В html тоже нужно добавлять отступы у вложенных элементов

2018-10-25 19:21 UTC, PolinaShneider commented on reactions.js
> +  var d = document.createElement('div');
Этого не должно быть в конструкторе

2018-10-25 19:21 UTC, PolinaShneider commented on reactions.js
> +    console.log(2);
Убрать лог

2018-10-26 20:52 UTC, PolinaShneider requested changes

2018-10-26 20:52 UTC, PolinaShneider commented on reactions.js
> +button.classList.toggle('buttonfocus');
Сейчас ты выполняешь classList.toggle сразу при выполнении скрипта. А тебе нужно менять класс при пользовательском клике. Это делается вот так:

`button.addEventListener('click', function () {
    this.classList.toggle('buttonfocus');
})`

То же самое, что и 

`button.addEventListener('click', function () {
    button.classList.toggle('buttonfocus');
})`

2018-10-26 20:55 UTC, PolinaShneider commented on reactions.html
> +<div class=block></div>
`<div class="block"></div>`

Добавь двойные кавычки у имени класса

2018-10-26 20:56 UTC, PolinaShneider commented on reactions.css
> +		position: static;
Можешь найти картинки в нормальном качестве?

Можно взять отсюда: https://emojipedia.org/grinning-face/

2018-10-27 19:36 UTC, PolinaShneider requested changes

2018-10-27 19:36 UTC, PolinaShneider commented on reactions.css
> +    /*background-color: green;*/
Убрать закомментированные значения стилей. Их быть не должно. Высоту и ширину в процентах лучше не задавать. Свойство `position: static;` — по умолчанию. Избавиться от него. Назвать классы по БЭМу

2018-10-27 19:36 UTC, PolinaShneider commented on reactions.css
> +.blocktext {
Сейчас этот блок у тебя пустой. Либо избавься от него, либо сверстай так, чтобы он нес в себе информацию.

2018-10-27 19:36 UTC, PolinaShneider commented on reactions.css
> +    float: right;
Разберись со флоатами — из-за них у тебя сейчас происходит выпадание из родительского контейнера.

2018-10-27 19:36 UTC, PolinaShneider commented on reactions.css
> +    position: static;
Пройдись по всем свойствам в инспекторе. У тебя сейчас есть лишние. Если выключение свойства ничего не меняет, его можно смело удалить.

2018-10-27 19:36 UTC, PolinaShneider commented on reactions.css
> +    background-color: #FF5252;
`border-color` лишнее. У тебя задается цвет в `border`

2018-10-29 22:50 UTC, PolinaShneider approved these changes

2018-10-29 22:53 UTC, merged